Document: qtpfsgui
Title: Debian qtpfsgui Manual
Author: <insert document author here>
Abstract: This manual describes what qtpfsgui is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/qtpfsgui/qtpfsgui.sgml.gz

Format: postscript
Files: /usr/share/doc/qtpfsgui/qtpfsgui.ps.gz

Format: text
Files: /usr/share/doc/qtpfsgui/qtpfsgui.text.gz

Format: HTML
Index: /usr/share/doc/qtpfsgui/html/index.html
Files: /usr/share/doc/qtpfsgui/html/*.html

  
